version: "3"
services:
  emba:
    image: embeddedanalyzer/emba:latest
    build: .
    privileged: true
    volumes:
        - ${FIRMWARE}/:/firmware:ro
        - ${LOG}/:/log
        - ${EMBA}/:/emba:ro
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
    network_mode: "host"
    environment:
        - USER
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
