version: "3"
services:
  emba:
    image: embeddedanalyzer/emba:latest
    read_only: true
    # all pre-checker mount modules need privileged mode
    privileged: true
    # /root is needed for binwalk
    # /tmp is needed for FACT extractor
    tmpfs:
      - /tmp
      - /root
      - /run
      - /var/run
    build: .
    # dev is needed for the system emulator (L10)
    volumes:
        - ${FIRMWARE}/:/firmware:ro
        - ${LOG}/:/log
        - ${EMBA}/:/emba:ro
        - ${EMBA}/external/firmae/scripts:/external/firmae/scripts:ro
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
        - /dev:/dev
    environment:
        - USER
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    networks:
      - emba_runs
    ulimits:
      core:
        hard: 0
        soft: 0

networks:
  emba_runs:
    name: emba_runs
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.name: emba_runs
    ipam:
      config:
        - subnet: "172.36.0.0/16"
