version: "3"
services:
  emba:
    image: embeddedanalyzer/emba:latest
    read_only: false
    privileged: true
    tmpfs:
      - /tmp
      - /root
      - /var/run
      - /var/lock
    build: .
    volumes:
        - ${FIRMWARE}/:/firmware:ro
        - ${LOG}/:/log
        - ${EMBA}/:/emba:ro
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
    environment:
        - USER
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    networks:
      - emba_runs
    ulimits:
      core:
        hard: 0
        soft: 0

networks:
  emba_runs:
    name: emba_runs
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.name: emba_runs
    ipam:
      config:
        - subnet: "172.36.0.0/16"
