version: "3"
services:
  emba:
    build: .
    volumes:
        - ${FIRMWARE}/:/firmware
        - ${LOG}/:/log
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/:/tmp/
    network_mode: "host"
    environment:
        - USER
