version: "3"
services:
  emba:
    build: .
    privileged: true
    volumes:
        - ${FIRMWARE}/:/firmware
        - ${LOG}/:/log
        - ${EMBA}/:/emba:ro
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/:/tmp/
    network_mode: "host"
    environment:
        - USER
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
