name: Docker Image build

on:
  push:
    branches:    
      - '**'        # matches every branch
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v3
    - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
    - name: Build EMBA Docker image
      run: docker-compose build --no-cache --pull
