name: Docker Image build

on:
  schedule:
    - cron: '0 0 * * *' # do it every day
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker-build:
    #    if: github.repository_owner == 'e-m-b-a'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      - name: Build EMBA Docker image
        uses: Wandalen/wretry.action@master
        with:
          run: docker-compose build --no-cache --pull && ./emba -d -y -j
          attempt_limit: 3
