name: EMBA Docker Image build

on:
  schedule:
    - cron: '0 0 * * *' # do it every day

jobs:
  docker-build:
    if: github.repository_owner == 'e-m-b-a'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true
      - name: EMBA container build
        uses: Wandalen/wretry.action@master
        with:
          command: docker-compose build --no-cache --pull && ./emba -d 2 -y -j
          attempt_limit: 3
